services:
  vaporfetch:
    image: ghcr.io/theretrogeekyt-dev/vaporfetch:latest
    pull_policy: always
    container_name: vaporfetch
    platform: linux/amd64
    restart: unless-stopped
    security_opt:
      - seccomp=unconfined
    ports:
      - "8080:8080"
    environment:
      - DEFAULT_PLATFORM=windows
      - VALIDATE_DOWNLOADS=true
      - STEAM_FORCE_IPV4=1
      - PORT=8080
    volumes:
      - ./data:/data
      - ./downloads:/downloads
      - ./data/steam_root:/root/.steam
      - ./data/steam_home:/root/Steam
      - ./data/steam_share:/root/.local/share/Steam
